In [ ]:
import polars as pl

# 1. Загрузка исходных сырых данных (до генерации фичей)
data_path = "../data/raw/"
df_clients = pl.read_csv(f"{data_path}clients.csv", try_parse_dates=True)          # Справочник клиентов
df_monthly = pl.read_csv(f"{data_path}monthly_client.csv", try_parse_dates=True)   # Ежемесячная активность
df_nso     = pl.read_csv(f"{data_path}monthly_nso.csv", try_parse_dates=True)      # Данные по депозитам
df_kp = pl.read_csv(f"{data_path}kp.csv")

# 2. Агрегируем данные по депозитам (НСО) до уровня клиент + дата
nso_agg = df_nso.group_by(["client_id", "report_date"]).agg([
    pl.col("early_close_flag").max().alias("nso_early_close_any"),
    pl.col("outflow_amt").sum().alias("nso_outflow_sum"),
])

# 3. Объединяем ежемесячную активность со срочными вкладами и справочником
df_full_profile = (
    df_monthly
    .join(nso_agg, on=["client_id", "report_date"], how="left")
    .join(df_clients, on="client_id", how="left")
    .with_columns(
        pl.col("nso_early_close_any", "nso_outflow_sum").fill_null(0),
        # Расчет возраста клиента в месяцах на момент среза данных
        ((pl.col("report_date") - pl.col("registration_date")).dt.total_days() / 30.4).alias("client_age_months")
    )
)

# 4. Берем самый последний доступный месяц для каждого клиента, чтобы получить актуальный профиль
client_profiles_table = (
    df_full_profile
    .sort(["client_id", "report_date"])
    .unique(subset=["client_id"], keep="last") # Оставляет только последнюю хронологическую строчку для каждого клиента
    .drop(["registration_date", "cpr_id_right", "kp_id_right", "segment_name_right", "has_salary_project_right"]) # Удаляем техническую дату, так как посчитали возраст в месяцах
)
## Блок переноса названия отрасли в начало таблицы
client_profiles_table = client_profiles_table.join(df_kp, on="kp_id", how="left")
cols = client_profiles_table.columns
cols.remove("kp_name")                    # Убираем из конца
target_idx = cols.index("kp_id") + 1      # Находим индекс kp_id и смещаемся на 1 вправо
cols.insert(target_idx, "kp_name")        # Вставляем kp_name на нужное место
# 3. Применяем новый порядок
client_profiles_table = client_profiles_table.select(cols)
# Настройка отображения, чтобы Polars показал все столбцы профиля в Jupyter
with pl.Config(tbl_cols=-1, tbl_rows=10):
    print(f"Всего сформировано профилей для {client_profiles_table.height} уникальных клиентов.")
    display(client_profiles_table.head(20))
client_profiles_table.select(pl.col('client_id').n_unique())

Всего сформировано профилей для 3000 уникальных клиентов.

shape: (20, 74)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ rep ┆ cli ┆ cpr ┆ kp_ ┆ kp_ ┆ seg ┆ dem ┆ dem ┆ dem ┆ bal ┆ bal ┆ bal ┆ bal ┆ bal ┆ bal ┆ nso ┆ nso ┆ nso ┆ nso ┆ nso ┆ nso ┆ avg ┆ tot ┆ txn ┆ txn ┆ txn ┆ txn ┆ txn ┆ txn ┆ txn ┆ txn ┆ txn ┆ txn ┆ txn ┆ act ┆ txn ┆ txn ┆ txn ┆ txn ┆ txn ┆ uni ┆ tar ┆ tar ┆ op3 ┆ op7 ┆ op7 ┆ op1 ┆ net ┆ out ┆ out ┆ amt ┆ has ┆ act ┆ cre ┆ cre ┆ cre ┆ cre ┆ cre ┆ has ┆ sal ┆ sal ┆ sal ┆ sal ┆ sal ┆ sal ┆ key ┆ mon ┆ mon ┆ mon ┆ is_ ┆ nso ┆ nso ┆ emp ┆ cli │
│ ort ┆ ent ┆ _id ┆ id  ┆ nam ┆ men ┆ and ┆ and ┆ and ┆ _mi ┆ _ma ┆ _me ┆ _st ┆ _cv ┆ _da ┆ _ba ┆ _ba ┆ _ba ┆ _in ┆ _pr ┆ _ac ┆ _ra ┆ al_ ┆ _ba ┆ _cn ┆ _cn ┆ _cn ┆ _am ┆ _am ┆ _am ┆ _ma ┆ _av ┆ _me ┆ _st ┆ ive ┆ _se ┆ _ot ┆ _in ┆ _ex ┆ _ot ┆ q_c ┆ get ┆ get ┆ _am ┆ _am ┆ _cn ┆ 0_a ┆ _fl ┆ flo ┆ _ba ┆ _pd ┆ _cr ┆ ive ┆ dit ┆ dit ┆ dit ┆ dit ┆ dit ┆ _sa ┆ ary ┆ ary ┆ ary ┆ ary ┆ ary ┆ ary ┆ _ra ┆ th_ ┆ th_ ┆ th_ ┆ qua ┆ _ea ┆ _ou ┆ loy ┆ ent │
│ _da ┆ _id ┆ --- ┆ --- ┆ e   ┆ t_n ┆ _ba ┆ _ba ┆ _ba ┆ n   ┆ x   ┆ dia ┆ d   ┆ --- ┆ ys  ┆ lan ┆ lan ┆ lan ┆ ter ┆ inc ┆ tiv ┆ te  ┆ lia ┆ l_a ┆ t   ┆ t_i ┆ t_o ┆ t   ┆ t_i ┆ t_o ┆ x_a ┆ g_a ┆ dia ┆ d_a ┆ _da ┆ lf_ ┆ her ┆ t_a ┆ t_a ┆ h_b ┆ a_c ┆ _ou ┆ _ou ┆ t   ┆ t   ┆ t   ┆ mt  ┆ ow_ ┆ w_s ┆ l_a ┆ --- ┆ edi ┆ _cr ┆ _li ┆ _de ┆ _pa ┆ _ut ┆ _ov ┆ lar ┆ _pr ┆ _pr ┆ _em ┆ _fu ┆ _av ┆ _mo ┆ te  ┆ num ┆ sin ┆ cos ┆ rte ┆ rly ┆ tfl ┆ ee_ ┆ _ag │
│ te  ┆ --- ┆ str ┆ str ┆ --- ┆ ame ┆ lan ┆ lan ┆ lan ┆ --- ┆ --- ┆ n   ┆ --- ┆ f64 ┆ --- ┆ ce_ ┆ ce_ ┆ ce_ ┆ est ┆ ipa ┆ e_t ┆ --- ┆ bil ┆ mt  ┆ --- ┆ n   ┆ ut  ┆ --- ┆ n   ┆ ut  ┆ mt  ┆ mt  ┆ n_a ┆ mt  ┆ ys  ┆ amt ┆ _am ┆ mt  ┆ mt  ┆ ank ┆ nt  ┆ tfl ┆ tfl ┆ --- ┆ --- ┆ --- ┆ --- ┆ amt ┆ har ┆ mt  ┆ f64 ┆ t   ┆ edi ┆ mit ┆ bt_ ┆ yme ┆ il  ┆ erd ┆ y_p ┆ oje ┆ oje ┆ plo ┆ nd_ ┆ g_p ┆ nth ┆ --- ┆ --- ┆ --- ┆ --- ┆ r_e ┆ _cl ┆ ow_ ┆ cnt ┆ e_m │
│ --- ┆ str ┆     ┆     ┆ str ┆ --- ┆ ce_ ┆ ce_ ┆ ce_ ┆ f64 ┆ f64 ┆ --- ┆ f64 ┆     ┆ i64 ┆ sta ┆ end ┆ avg ┆ _pa ┆ l_o ┆ ype ┆ f64 ┆ iti ┆ --- ┆ i64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ mt  ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ --- ┆ _am ┆ --- ┆ ow_ ┆ ow_ ┆ f64 ┆ f64 ┆ i64 ┆ f64 ┆ --- ┆ e   ┆ --- ┆     ┆ --- ┆ t_c ┆ _am ┆ amt ┆ nt_ ┆ --- ┆ ue_ ┆ roj ┆ ct_ ┆ ct_ ┆ yee ┆ amt ┆ aym ┆ s_w ┆ f64 ┆ i64 ┆ f64 ┆ f64 ┆ nd  ┆ ose ┆ sum ┆ _st ┆ ont │
│ dat ┆     ┆     ┆     ┆     ┆ str ┆ sta ┆ end ┆ avg ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ rt  ┆ --- ┆ --- ┆ id_ ┆ utf ┆ s_c ┆     ┆ es_ ┆ f64 ┆     ┆ i64 ┆ i64 ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ f64 ┆ i64 ┆ f64 ┆ --- ┆ f64 ┆ f64 ┆ t   ┆ i64 ┆ amt ┆ cnt ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ f64 ┆     ┆ i64 ┆ nt  ┆ t   ┆ --- ┆ amt ┆ f64 ┆ fla ┆ ect ┆ dt  ┆ mon ┆ _cn ┆ --- ┆ ent ┆ ith ┆     ┆     ┆     ┆     ┆ --- ┆ _an ┆ --- ┆ art ┆ hs  │
│ e   ┆     ┆     ┆     ┆     ┆     ┆ rt  ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ f64 ┆ amt ┆ low ┆ nt  ┆     ┆ end ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆ --- ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ --- ┆ --- ┆ f64 ┆ --- ┆     ┆ g   ┆ --- ┆ --- ┆ ths ┆ t   ┆ f64 ┆ _pe ┆ out ┆     ┆     ┆     ┆     ┆ i64 ┆ y   ┆ f64 ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆ --- ┆ _am ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ f64 ┆     ┆ f64 ┆     ┆ --- ┆ i64 ┆ i64 ┆ --- ┆ --- ┆     ┆ r_e ┆ _pa ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ i64 ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ t   ┆ i64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ mpl ┆ y_1 ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oye ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ CL0 ┆ CPR ┆ KP0 ┆ Доб ┆ MAS ┆ 1.8 ┆ 226 ┆ 2.0 ┆ 1.1 ┆ 2.3 ┆ 226 ┆ 312 ┆ 0.1 ┆ 31  ┆ 785 ┆ 794 ┆ 790 ┆ 136 ┆ 942 ┆ 1   ┆ 20. ┆ 306 ┆ 226 ┆ 35  ┆ 16  ┆ 19  ┆ 3.5 ┆ 1.9 ┆ 1.5 ┆ 581 ┆ 101 ┆ 907 ┆ 695 ┆ 17  ┆ 0.0 ┆ 2.9 ┆ 1.0 ┆ 476 ┆ 238 ┆ 5   ┆ 0.0 ┆ 0   ┆ 912 ┆ 0.0 ┆ 0   ┆ 0.0 ┆ 457 ┆ 0.4 ┆ 1.5 ┆ 114 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 16. ┆ 5   ┆ 0.5 ┆ -0. ┆ 0   ┆ 0   ┆ 942 ┆ 0   ┆ 150 │
│ 6-0 ┆ 000 ┆ 000 ┆ 1   ┆ ыча ┆ S   ┆ 106 ┆ 772 ┆ 392 ┆ 530 ┆ 405 ┆ 772 ┆ 726 ┆ 379 ┆     ┆ 127 ┆ 978 ┆ 052 ┆ 04. ┆ 1.2 ┆     ┆ 33  ┆ 270 ┆ 772 ┆     ┆     ┆     ┆ 419 ┆ 995 ┆ 424 ┆ 382 ┆ 196 ┆ 69. ┆ 36. ┆     ┆     ┆ 225 ┆ 662 ┆ 134 ┆ 154 ┆     ┆     ┆     ┆ 704 ┆     ┆     ┆     ┆ 139 ┆ 355 ┆ 424 ┆ 254 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 967 ┆     ┆     ┆ 866 ┆     ┆     ┆ 1.2 ┆     ┆ .09 │
│ 5-3 ┆ 001 ┆ 639 ┆     ┆ и   ┆     ┆ e6  ┆ 3.7 ┆ e6  ┆ e6  ┆ e6  ┆ 3.7 ┆ .67 ┆     ┆     ┆ .69 ┆ .01 ┆ .85 ┆ 16  ┆ 2   ┆     ┆     ┆ 1.7 ┆ 3.7 ┆     ┆     ┆     ┆ e6  ┆ e6  ┆ e6  ┆ .51 ┆ .68 ┆ 12  ┆ 46  ┆     ┆     ┆ e6  ┆ e6  ┆ .34 ┆ .25 ┆     ┆     ┆     ┆ .4  ┆     ┆     ┆     ┆ .5  ┆     ┆ e6  ┆ .31 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 175 ┆     ┆     ┆ 025 ┆     ┆     ┆ 2   ┆     ┆ 868 │
│ 1   ┆     ┆     ┆     ┆ сыр ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   │
│     ┆     ┆     ┆     ┆ ье  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ CL0 ┆ CPR ┆ KP1 ┆ АПК ┆ Alf ┆ 3.9 ┆ 113 ┆ 2.0 ┆ 113 ┆ 5.2 ┆ 5.1 ┆ 1.9 ┆ 0.3 ┆ 31  ┆ 3.1 ┆ 3.1 ┆ 3.1 ┆ 455 ┆ 366 ┆ 3   ┆ 18. ┆ 3.2 ┆ 113 ┆ 45  ┆ 22  ┆ 23  ┆ 7.2 ┆ 1.6 ┆ 557 ┆ 964 ┆ 161 ┆ 119 ┆ 152 ┆ 16  ┆ 0.0 ┆ 2.1 ┆ 5.2 ┆ 305 ┆ 208 ┆ 9   ┆ 0.0 ┆ 0   ┆ 131 ┆ 0.0 ┆ 0   ┆ 5.0 ┆ -3. ┆ 0.7 ┆ 557 ┆ 234 ┆ 1   ┆ 1   ┆ 1.9 ┆ 404 ┆ 417 ┆ 0.2 ┆ 0   ┆ 1   ┆ 200 ┆ 66  ┆ 115 ┆ 5.0 ┆ 442 ┆ 0   ┆ 16. ┆ 5   ┆ 0.5 ┆ -0. ┆ 0   ┆ 0   ┆ 366 ┆ 129 ┆ 315 │
│ 6-0 ┆ 000 ┆ 000 ┆ 0   ┆     ┆ a   ┆ 954 ┆ 730 ┆ 545 ┆ 730 ┆ 852 ┆ 991 ┆ 907 ┆ 829 ┆     ┆ 326 ┆ 416 ┆ 371 ┆ 20. ┆ 18. ┆     ┆ 35  ┆ 553 ┆ 730 ┆     ┆     ┆     ┆ 639 ┆ 911 ┆ 277 ┆ 015 ┆ 420 ┆ 229 ┆ 066 ┆     ┆     ┆ 007 ┆ 672 ┆ 584 ┆ 183 ┆     ┆     ┆     ┆ 383 ┆     ┆     ┆ 853 ┆ 881 ┆ 672 ┆ 277 ┆ 319 ┆     ┆     ┆ 313 ┆ 006 ┆ 0.0 ┆ 092 ┆     ┆     ┆ 5   ┆     ┆     ┆ 853 ┆ 20. ┆     ┆ 967 ┆     ┆     ┆ 866 ┆     ┆     ┆ 18. ┆     ┆ .49 │
│ 5-3 ┆ 002 ┆ 581 ┆     ┆     ┆ Onl ┆ e6  ┆ .1  ┆ e6  ┆ .1  ┆ e6  ┆ e6  ┆ e6  ┆     ┆     ┆ e6  ┆ e6  ┆ e6  ┆ 95  ┆ 18  ┆     ┆     ┆ e6  ┆ .1  ┆     ┆     ┆     ┆ e6  ┆ e6  ┆ 4.9 ┆ .32 ┆ .31 ┆ .83 ┆ .95 ┆     ┆     ┆ e6  ┆ e6  ┆ .12 ┆ .97 ┆     ┆     ┆     ┆ .12 ┆     ┆     ┆ e6  ┆ 6e6 ┆     ┆ 4.9 ┆ .8  ┆     ┆     ┆ e6  ┆ .87 ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆ e6  ┆ 29  ┆     ┆ 175 ┆     ┆     ┆ 025 ┆     ┆     ┆ 18  ┆     ┆ 342 │
│ 1   ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│ 202 ┆ CL0 ┆ CPR ┆ KP0 ┆ Нед ┆ MAS ┆ 436 ┆ 136 ┆ 2.2 ┆ 0.0 ┆ 5.3 ┆ 1.1 ┆ 1.9 ┆ 1.8 ┆ 31  ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0   ┆ nul ┆ 136 ┆ 136 ┆ 56  ┆ 27  ┆ 29  ┆ 9.1 ┆ 2.4 ┆ 6.7 ┆ 358 ┆ 163 ┆ 100 ┆ 184 ┆ 20  ┆ 0.0 ┆ 3.2 ┆ 618 ┆ 519 ┆ 228 ┆ 7   ┆ 0.0 ┆ 0   ┆ 474 ┆ 0.0 ┆ 0   ┆ 5.7 ┆ -4. ┆ 0.7 ┆ 6.7 ┆ 295 ┆ 1   ┆ 1   ┆ 3.1 ┆ 642 ┆ 201 ┆ 0.2 ┆ 0   ┆ 1   ┆ 111 ┆ 37  ┆ 97  ┆ 5.7 ┆ 588 ┆ 0   ┆ 16. ┆ 5   ┆ 0.5 ┆ -0. ┆ 0   ┆ 0   ┆ 0.0 ┆ 97  ┆ 286 │
│ 6-0 ┆ 000 ┆ 000 ┆ 8   ┆ виж ┆ S   ┆ 389 ┆ 735 ┆ 503 ┆     ┆ 566 ┆ 034 ┆ 943 ┆ 075 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ 735 ┆ 735 ┆     ┆     ┆     ┆ 729 ┆ 729 ┆ 000 ┆ 594 ┆ 802 ┆ 773 ┆ 210 ┆     ┆     ┆ 835 ┆ 005 ┆ 992 ┆ 811 ┆     ┆     ┆     ┆ 417 ┆     ┆     ┆ 096 ┆ 227 ┆ 304 ┆ 000 ┆ 900 ┆     ┆     ┆ 013 ┆ 252 ┆ 31. ┆ 071 ┆     ┆     ┆ 2   ┆     ┆     ┆ 096 ┆ 61. ┆     ┆ 967 ┆     ┆     ┆ 866 ┆     ┆     ┆     ┆     ┆ .34 │
│ 5-3 ┆ 003 ┆ 075 ┆     ┆ имо ┆     ┆ 8.6 ┆ .57 ┆ e6  ┆     ┆ e6  ┆ e6  ┆ e6  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .57 ┆ .57 ┆     ┆     ┆     ┆ e6  ┆ e6  ┆ e6  ┆ .86 ┆ .19 ┆ .54 ┆ .22 ┆     ┆     ┆ e6  ┆ 0.7 ┆ .03 ┆ .05 ┆     ┆     ┆     ┆ .28 ┆     ┆     ┆ e6  ┆ 2e6 ┆     ┆ e6  ┆ .72 ┆     ┆     ┆ e6  ┆ .9  ┆ 07  ┆     ┆     ┆     ┆     ┆     ┆     ┆ e6  ┆ 36  ┆     ┆ 175 ┆     ┆     ┆ 025 ┆     ┆     ┆     ┆     ┆ 868 │
│ 1   ┆     ┆     ┆     ┆ сть ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   │
│ 202 ┆ CL0 ┆ CPR ┆ KP1 ┆ АПК ┆ MAS ┆ 2.3 ┆ 2.8 ┆ 2.5 ┆ 1.8 ┆ 288 ┆ 214 ┆ 379 ┆ 0.1 ┆ 31  ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 329 ┆ 107 ┆ 3   ┆ 19. ┆ 4.9 ┆ 2.8 ┆ 38  ┆ 15  ┆ 23  ┆ 3.1 ┆ 1.8 ┆ 1.3 ┆ 433 ┆ 821 ┆ 515 ┆ 987 ┆ 31  ┆ 0.0 ┆ 2.8 ┆ 496 ┆ 820 ┆ 273 ┆ 5   ┆ 0.0 ┆ 0   ┆ 286 ┆ 0.0 ┆ 0   ┆ 0.0 ┆ 486 ┆ 0.4 ┆ 1.3 ┆ 100 ┆ 1   ┆ 1   ┆ 292 ┆ 147 ┆ 957 ┆ 0.5 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 16. ┆ 5   ┆ 0.5 ┆ -0. ┆ 0   ┆ 0   ┆ 107 ┆ 0   ┆ 254 │
│ 6-0 ┆ 000 ┆ 000 ┆ 0   ┆     ┆ S   ┆ 401 ┆ 268 ┆ 834 ┆ 643 ┆ 504 ┆ 334 ┆ 381 ┆ 77  ┆     ┆ 151 ┆ 870 ┆ 510 ┆ 48. ┆ 27. ┆     ┆ 37  ┆ 137 ┆ 268 ┆     ┆     ┆     ┆ 199 ┆ 033 ┆ 166 ┆ 878 ┆ 02. ┆ 78. ┆ 58. ┆     ┆     ┆ 186 ┆ 585 ┆ 018 ┆ 944 ┆     ┆     ┆     ┆ 086 ┆     ┆     ┆     ┆ 679 ┆ 22  ┆ 166 ┆ 641 ┆     ┆     ┆ 301 ┆ 138 ┆ 5.8 ┆ 034 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 967 ┆     ┆     ┆ 866 ┆     ┆     ┆ 27. ┆     ┆ .17 │
│ 5-3 ┆ 004 ┆ 027 ┆     ┆     ┆     ┆ e6  ┆ e6  ┆ e6  ┆ 12e ┆ 9.3 ┆ 1.1 ┆ .99 ┆     ┆     ┆ e6  ┆ e6  ┆ e6  ┆ 27  ┆ 86  ┆     ┆     ┆ e6  ┆ e6  ┆     ┆     ┆     ┆ e6  ┆ e6  ┆ e6  ┆ .92 ┆ 3   ┆ 0   ┆ 39  ┆     ┆     ┆ e6  ┆ .19 ┆ .65 ┆ .8  ┆     ┆     ┆     ┆ .52 ┆     ┆     ┆     ┆ .78 ┆     ┆ e6  ┆ .53 ┆     ┆     ┆ .63 ┆ .4  ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 175 ┆     ┆     ┆ 025 ┆     ┆     ┆ 86  ┆     ┆ 763 │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   │
│ 202 ┆ CL0 ┆ CPR ┆ KP1 ┆ АПК ┆ MAS ┆ 578 ┆ 230 ┆ 300 ┆ 0.0 ┆ 1.0 ┆ 578 ┆ 292 ┆ 0.5 ┆ 31  ┆ 251 ┆ 253 ┆ 252 ┆ 357 ┆ 345 ┆ 1   ┆ 17. ┆ 276 ┆ 230 ┆ 34  ┆ 14  ┆ 20  ┆ 1.7 ┆ 572 ┆ 1.1 ┆ 122 ┆ 500 ┆ 391 ┆ 546 ┆ 15  ┆ 0.0 ┆ 588 ┆ 1.1 ┆ 925 ┆ 721 ┆ 8   ┆ 0.0 ┆ 0   ┆ 815 ┆ 0.0 ┆ 0   ┆ 1.0 ┆ -55 ┆ 0.6 ┆ 1.1 ┆ 548 ┆ 1   ┆ 3   ┆ 787 ┆ 160 ┆ 931 ┆ 0.2 ┆ 0   ┆ 1   ┆ 914 ┆ 30  ┆ 115 ┆ 1.0 ┆ 952 ┆ 0   ┆ 16. ┆ 5   ┆ 0.5 ┆ -0. ┆ 0   ┆ 0   ┆ 345 ┆ 115 ┆ 47. │
│ 6-0 ┆ 000 ┆ 000 ┆ 0   ┆     ┆ S   ┆ 657 ┆ 21. ┆ 839 ┆     ┆ 270 ┆ 657 ┆ 711 ┆ 058 ┆     ┆ 072 ┆ 271 ┆ 171 ┆ 6.6 ┆ 2.9 ┆     ┆ 68  ┆ 292 ┆ 21. ┆     ┆     ┆     ┆ 004 ┆ 403 ┆ 280 ┆ 566 ┆ 13. ┆ 24. ┆ 04. ┆     ┆     ┆ 225 ┆ 188 ┆ 0.3 ┆ 3.7 ┆     ┆     ┆     ┆ 6.3 ┆     ┆     ┆ 956 ┆ 563 ┆ 634 ┆ 280 ┆ 52. ┆     ┆     ┆ 806 ┆ 204 ┆ .0  ┆ 034 ┆     ┆     ┆     ┆     ┆     ┆ 956 ┆ 7.1 ┆     ┆ 967 ┆     ┆     ┆ 866 ┆     ┆     ┆ 2.9 ┆     ┆ 664 │
│ 5-3 ┆ 005 ┆ 254 ┆     ┆     ┆     ┆ .14 ┆ 21  ┆ .17 ┆     ┆ e6  ┆ .14 ┆ .42 ┆     ┆     ┆ .65 ┆ .24 ┆ .94 ┆ 6   ┆ 6   ┆     ┆     ┆ .44 ┆ 21  ┆     ┆     ┆     ┆ e6  ┆ .15 ┆ e6  ┆ .68 ┆ 01  ┆ 03  ┆ 31  ┆     ┆     ┆ .0  ┆ e6  ┆ 6   ┆ 8   ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆ e6  ┆ 5.9 ┆     ┆ e6  ┆ 98  ┆     ┆     ┆ .67 ┆ .6  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e6  ┆ 1   ┆     ┆ 175 ┆     ┆     ┆ 025 ┆     ┆     ┆ 6   ┆     ┆ 474 │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 202 ┆ CL0 ┆ CPR ┆ KP1 ┆ Усл ┆ MAS ┆ 927 ┆ 966 ┆ 947 ┆ 808 ┆ 1.1 ┆ 927 ┆ 970 ┆ 0.1 ┆ 31  ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0   ┆ nul ┆ 966 ┆ 966 ┆ 16  ┆ 5   ┆ 11  ┆ 865 ┆ 452 ┆ 412 ┆ 147 ┆ 540 ┆ 419 ┆ 557 ┆ 10  ┆ 0.0 ┆ 797 ┆ 282 ┆ 130 ┆ 853 ┆ 6   ┆ 0.0 ┆ 0   ┆ 999 ┆ 0.0 ┆ 0   ┆ 0.0 ┆ 393 ┆ 0.4 ┆ 412 ┆ 279 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 16. ┆ 5   ┆ 0.5 ┆ -0. ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 234 │
│ 6-0 ┆ 000 ┆ 000 ┆ 1   ┆ уги ┆ S   ┆ 539 ┆ 860 ┆ 199 ┆ 669 ┆ 821 ┆ 539 ┆ 43. ┆ 046 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ 860 ┆ 860 ┆     ┆     ┆     ┆ 155 ┆ 238 ┆ 917 ┆ 882 ┆ 72. ┆ 25. ┆ 74. ┆     ┆     ┆ 874 ┆ 834 ┆ 082 ┆ 70. ┆     ┆     ┆     ┆ 83. ┆     ┆     ┆     ┆ 21. ┆ 773 ┆ 917 ┆ 08. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 967 ┆     ┆     ┆ 866 ┆     ┆     ┆     ┆     ┆ .86 │
│ 5-3 ┆ 016 ┆ 618 ┆     ┆     ┆     ┆ .23 ┆ .45 ┆ .84 ┆ .8  ┆ e6  ┆ .23 ┆ 71  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .45 ┆ .45 ┆     ┆     ┆     ┆ .82 ┆ .52 ┆ .3  ┆ .47 ┆ 24  ┆ 56  ┆ 76  ┆     ┆     ┆ .45 ┆ .8  ┆ .5  ┆ 15  ┆     ┆     ┆     ┆ 18  ┆     ┆     ┆     ┆ 22  ┆     ┆ .3  ┆ 25  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 175 ┆     ┆     ┆ 025 ┆     ┆     ┆     ┆     ┆ 842 │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│ 202 ┆ CL0 ┆ CPR ┆ KP0 ┆ Доб ┆ MAS ┆ 162 ┆ 105 ┆ 134 ┆ 105 ┆ 168 ┆ 118 ┆ 210 ┆ 0.1 ┆ 31  ┆ 197 ┆ 202 ┆ 200 ┆ 312 ┆ 113 ┆ 3   ┆ 19. ┆ 307 ┆ 105 ┆ 34  ┆ 18  ┆ 16  ┆ 124 ┆ 336 ┆ 908 ┆ 160 ┆ 366 ┆ 276 ┆ 236 ┆ 12  ┆ 0.0 ┆ 645 ┆ 669 ┆ 238 ┆ 100 ┆ 9   ┆ 0.0 ┆ 0   ┆ 129 ┆ 0.0 ┆ 0   ┆ 0.0 ┆ -57 ┆ 0.7 ┆ 908 ┆ 401 ┆ 1   ┆ 2   ┆ 746 ┆ 475 ┆ 109 ┆ 0.6 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 16. ┆ 5   ┆ 0.5 ┆ -0. ┆ 0   ┆ 0   ┆ 113 ┆ 0   ┆ 216 │
│ 6-0 ┆ 000 ┆ 000 ┆ 1   ┆ ыча ┆ S   ┆ 636 ┆ 390 ┆ 013 ┆ 390 ┆ 092 ┆ 524 ┆ 46. ┆ 776 ┆     ┆ 630 ┆ 390 ┆ 010 ┆ 9.8 ┆ 4.0 ┆     ┆ 5   ┆ 781 ┆ 390 ┆     ┆     ┆     ┆ 475 ┆ 14. ┆ 60. ┆ 52. ┆ 1.0 ┆ 4.2 ┆ 3.5 ┆     ┆     ┆ 05. ┆ 87. ┆ 73. ┆ 84. ┆     ┆     ┆     ┆ 61. ┆     ┆     ┆     ┆ 246 ┆ 299 ┆ 60. ┆ 5.3 ┆     ┆     ┆ 41. ┆ 11. ┆ 2.3 ┆ 365 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 967 ┆     ┆     ┆ 866 ┆     ┆     ┆ 4.0 ┆     ┆ .25 │
│ 5-3 ┆ 017 ┆ 415 ┆     ┆ и   ┆     ┆ .65 ┆ .54 ┆ .6  ┆ .54 ┆ .37 ┆ .72 ┆ 02  ┆     ┆     ┆ .67 ┆ .84 ┆ .75 ┆ 7   ┆ 8   ┆     ┆     ┆ .39 ┆ .54 ┆     ┆     ┆     ┆ .82 ┆ 86  ┆ 96  ┆ 39  ┆ 5   ┆ 4   ┆ 4   ┆     ┆     ┆ 35  ┆ 37  ┆ 6   ┆ 08  ┆     ┆     ┆     ┆ 38  ┆     ┆     ┆     ┆ .11 ┆     ┆ 96  ┆ 5   ┆     ┆     ┆ 71  ┆ 07  ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 175 ┆     ┆     ┆ 025 ┆     ┆     ┆ 9   ┆     ┆     │

shape: (1, 1)
┌───────────┐
│ client_id │
│ ---       │
│ u32       │
╞═══════════╡
│ 3000      │
└───────────┘

In [12]:
# 1. Проверяем точные названия столбцов и их типы в первой таблице
print("Таблица профилей:")
print(client_profiles_table.select(pl.col("kp_id")).schema)

# 2. Проверяем точные названия столбцов и их типы в файле kp.csv
print("\nСправочник kp.csv:")
print(df_kp.schema)

Таблица профилей:
Schema({'kp_id': String})

Справочник kp.csv:
Schema({'kp_id': String, 'kp_name': String})